- name: Generate Admin kubeconfig
  ansible.builtin.shell: >
    set -o errexit; \
    set -o pipefail; \
    kubectl config set-cluster kubernetes-the-hard-way \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://{{ hostvars['haproxy-lb'].ansible_host }}:6443 \
      --kubeconfig=admin.kubeconfig && \
                                     \
    kubectl config set-credentials admin \
      --client-certificate=admin.pem \
      --client-key=admin-key.pem \
      --embed-certs=true \
      --kubeconfig=admin.kubeconfig && \
                                     \
    kubectl config set-context default \
      --cluster=kubernetes-the-hard-way \
      --user=admin \
      --kubeconfig=admin.kubeconfig && \
                                       \
    kubectl config use-context default --kubeconfig=admin.kubeconfig
  args:
    executable: "/bin/bash"
    chdir: "{{ cert_conf }}"
    creates: "admin.kubeconfig"
