
- name: Generate Admin kubeconfig
  ansible.builtin.shell: >
    set -o errexit; \
    set -o pipefail; \
    kubectl config set-cluster kubernetes-the-hard-way \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://{{ hostvars['haproxy-lb'].ansible_host }}:6443 \
      --kubeconfig={{ item }}.kubeconfig && \
                                             \
    kubectl config set-credentials system:node:{{ item }} \
      --client-certificate={{ item }}.pem \
      --client-key={{ item  }}-key.pem \
      --embed-certs=true \
      --kubeconfig={{ item  }}.kubeconfig && \
                                             \
    kubectl config set-context default \
      --cluster=kubernetes-the-hard-way \
      --user=system:node:{{ item }} \
      --kubeconfig={{ item }}.kubeconfig && \
                                             \
    kubectl config use-context default --kubeconfig={{ item }}.kubeconfig
  args:
    executable: "/bin/bash"
    chdir: "{{ cert_conf }}"
    creates: "{{ inventory_hostname }}.kubeconfig"
  loop: "{{ groups['workers'] }}"

- name: Generate KubeProxy kubeconfig
  ansible.builtin.shell: >
    set -o errexit; \
    set -o pipefail; \
    kubectl config set-cluster kubernetes-the-hard-way \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://{{ hostvars['haproxy-lb'].ansible_host }}:6443 \
      --kubeconfig=kube-proxy.kubeconfig && \
                                            \
    kubectl config set-credentials system:kube-proxy \
      --client-certificate=kube-proxy.pem \
      --client-key=kube-proxy-key.pem \
      --embed-certs=true \
      --kubeconfig=kube-proxy.kubeconfig && \
                                            \
    kubectl config set-context default \
      --cluster=kubernetes-the-hard-way \
      --user=system:kube-proxy \
      --kubeconfig=kube-proxy.kubeconfig && \
                                            \
    kubectl config use-context default --kubeconfig=kube-proxy.kubeconfig
  args:
    executable: "/bin/bash"
    chdir: "{{ cert_conf }}"
    creates: "kube-proxy.kubeconfig"
 

