


- name: Template a file to /etc/files.conf
  template:
    src: core_dns.yaml.j2
    dest: "/tmp/core_dns.yaml"
  delegate_to: localhost

- name: Deploy OpenDNS to the cluster
  include_role:
     name: run_kubectl
  vars:
     yamlfile: "/tmp/core_dns.yaml"


