---
# This playbook prints a simple debug message
- name: Echo
  hosts: haproxy-lb
  connection: local
  gather_facts: False
  #  become: true

  vars:
     cert_conf: ./cert-conf
     cert_dir: ./certs

  roles:
    - certs
