---
# This playbook prints a simple debug message
- name: Bootstrap ETCD
  hosts: etcd
  #  connection: local
  gather_facts: False
  become: true

  vars:
     cert_conf: ./cert-conf
     cert_dir: ./certs
 
  roles:
    - etcd
