---
# This playbook prints a simple debug message
- name: Bootstrap Kube worker Nodes
  hosts: workers
  #  connection: local
  gather_facts: False
  become: true

  vars:
     cert_conf: ./cert-conf
     cert_dir: ./certs
 
  roles:
    - worker
