---
# This playbook prints a simple debug message
- name: Echo
  hosts: haproxy-lb
  connection: local
  gather_facts: False
  become: true


  tasks:
  - name: Disable SELinux
    ansible.posix.selinux:
      state: disabled

  - name: Install haproxy
    ansible.builtin.package:
      name: haproxy
      state: present

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /run/haproxy
      state: directory
      mode: '0755'
 
  - name: Create haproxy.cfg
    template: 
      src: "haproxy.conf.j2"
      dest: "/etc/haproxy/haproxy.cfg" 
      backup: true
    register: updated_haproxy_sysctl

  - name: Configure haproxy systemctl
    ansible.builtin.systemd_service:
      name: haproxy
      state: started
      enabled:  true
    register: updated_haproxy_sysctl
