- name: Create  CNI Bridge file
  ansible.builtin.template:
    src: "10-bridge.conf.j2"
    dest: "/etc/cni/net.d/10-bridge.conf"
#      owner: "{{ k8s_ca_certificate_owner }}"
#      group: "{{ k8s_ca_certificate_group }}"
#      mode: "{{ k8s_ca_file_perm }}"

- name: Create  CNI Loopback  file
  ansible.builtin.template:
    src: "99-loopback.conf.j2"
    dest: "/etc/cni/net.d/99-loopback.conf"
#      owner: "{{ k8s_ca_certificate_owner }}"
#      group: "{{ k8s_ca_certificate_group }}"
 
- name: Include Debian Netplan Roputes  tasks
  include_tasks:
       file: debian_static_routes.yaml
