- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0760'
  loop:
    - /etc/cni/net.d
    - /opt/cni/bin

- name: Download and Unarchive a CNI file 
  ansible.builtin.unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz
    dest: /opt/cni/bin/
    remote_src: yes

- name: Create  CNI Bridge file
  ansible.builtin.template:
    src: "10-bridge.conf.j2"
    dest: "/etc/cni/net.d/10-bridge.conf"
#      owner: "{{ k8s_ca_certificate_owner }}"
#      group: "{{ k8s_ca_certificate_group }}"
#      mode: "{{ k8s_ca_file_perm }}"

- name: Create  CNI Loopback  file
  ansible.builtin.template:
    src: "99-loopback.conf.j2"
    dest: "/etc/cni/net.d/99-loopback.conf"
#      owner: "{{ k8s_ca_certificate_owner }}"
#      group: "{{ k8s_ca_certificate_group }}"
 
- name: Add the br_netfilter module , fixes headaches with accessing services from pods
  community.general.modprobe:
    name: br_netfilter
    state: present
    persistent: present
 


