- name: Copy Encryption Config
  ansible.builtin.copy:
    src: "{{cert_conf }}/encryption-config.yaml"
    dest: "/var/lib/kubernetes/encryption-config.yaml"
    owner: root
    group: root
    mode: '0700'

- name: Get Kubenetes API binaries
  ansible.builtin.shell: >
    set -o errexit; \
    set -o pipefail; \
    wget -q --https-only --timestamping \
      "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kube-apiserver"
  args:
    executable: "/bin/bash"
    chdir: "/tmp"

- name: Copy the file to a new location
  ansible.builtin.copy:
    src: /tmp/kube-apiserver
    dest: /usr/local/bin/kube-apiserver
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Create kube-apiserver systemservice file
  ansible.builtin.template:
    src: "kube-apiserver.service.j2"
    dest: "/etc/systemd/system/kube-apiserver.service"
#      owner: "{{ k8s_ca_certificate_owner }}"
#      group: "{{ k8s_ca_certificate_group }}"
#      mode: "{{ k8s_ca_file_perm }}"

- name: Configure kube-apiserver systemctl
  ansible.builtin.systemd_service:
    name: kube-apiserver
    state: started
    enabled: true

- name: systemctl daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
