- name: Copy kube-scheduler Kubeconfigs
  ansible.builtin.copy:
    src: "{{ cert_conf }}/{{ item }}"
    dest: "/var/lib/kubernetes/{{ item }}"
    owner: root
    group: root
    mode: '0700'
  loop:
    - kube-scheduler.kubeconfig

- name: Create kube-scheduler.yaml
  ansible.builtin.template:
    src: "kube-scheduler.yaml.j2"
    dest: "/etc/kubernetes/config/kube-scheduler.yaml"
#      owner: "{{ k8s_ca_certificate_owner }}"
#      group: "{{ k8s_ca_certificate_group }}"
#      mode: "{{ k8s_ca_file_perm }}"

- name: Get Kube Scheduler binaries
  ansible.builtin.shell: >
    set -o errexit; \
    set -o pipefail; \
    wget -q --https-only --timestamping \
     "https://storage.googleapis.com/kubernetes-release/release/{{ k8s_version }}/bin/linux/amd64/kube-scheduler"
  args:
    executable: "/bin/bash"
    chdir: "/tmp"

- name: Copy the file to a new location
  ansible.builtin.copy:
    src: /tmp/kube-scheduler
    dest: /usr/local/bin/kube-scheduler
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Create Kube Scheduler service file
  ansible.builtin.template:
    src: "kube-scheduler.service.j2"
    dest: "/etc/systemd/system/kube-scheduler.service"
#      owner: "{{ k8s_ca_certificate_owner }}"
#      group: "{{ k8s_ca_certificate_group }}"
#      mode: "{{ k8s_ca_file_perm }}"

- name: Configure Kube Scheduler systemctl
  ansible.builtin.systemd_service:
    name: kube-scheduler
    state: started
    enabled: true

- name: systemctl daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true



