- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0760'
  loop:
     - /etc/kubernetes/config
     - /var/lib/kubernetes
     - ~root/.kube

- name: Copy Certificates
  ansible.builtin.copy:
    src: "{{ cert_conf }}/{{ item }}"
    dest: "/var/lib/kubernetes/{{ item }}"
    owner: root
    group: root
    mode: '0700'
  loop:
    - ca.pem
    - ca-key.pem
    - kubernetes.pem
    - kubernetes-key.pem
    - service-account-key.pem
    - service-account.pem

- name: Copy Admin Kubeconfig
  ansible.builtin.copy:
    src: "{{ cert_conf }}/admin.kubeconfig"
    dest: "~vagrant/admin.kubeconfig"
    owner: vagrant
    group: vagrant
    mode: '0740'

- name: Copy Admin Kubeconfig to /root/.kube/config
  ansible.builtin.copy:
    src: "{{ cert_conf }}/admin.kubeconfig"
    dest: "~root/.kube/config"
    owner: vagrant
    group: vagrant
    mode: '0740'
 
- name: Get kubectl binaries
  ansible.builtin.shell: >
     set -o errexit; \
     set -o pipefail; \
     wget -q --https-only --timestamping \
      "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl"
  args:
    executable: "/bin/bash"
    chdir: "/tmp"

- name: Copy the file to a new location
  ansible.builtin.copy:
   src: /tmp/kubectl
   dest: /usr/local/bin/kubectl
   owner: root
   group: root
   mode: '0755'
   remote_src: yes
